# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.ioter.top
date_format: "ordinal"
#title: "KarlZheng's Homepage/Note"
title: "A geek"
#subtitle: "Thinking/Doing/Believe In"
subtitle: "KarlZheng's Notebook"
description: [Thinking/Doing/BelieveIn]
# ---------------- #
# ---------------- #
keywords: Karl, KarlZheng
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Karl Zheng
organization: ioter.top
organization_url: http://www.ioter.top
github_username: karlzheng
location: GuangZhou, China
email: zhengkarl@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: karlzheng.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
    #owner: mzlogin
    #repo: blog-comments
    #oauth:
        #client_id: d2e1cbbd298958076462
        #client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: karlzheng
    repo: karlzheng.github.io
    clientID: 37c3a59e1d2833fe4566
    clientSecret: 7ce1a3eadf2d67b8ab41cb87a4803a504a56ff8a

# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
#google:
    #analytics_id: UA-80669434-1
